# Generated by Django 4.2.13 on 2024-06-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(error_messages={'unique': 'Category already registered'}, max_length=50, unique=True),
        ),
    ]
